### ISSUE TITLE
Linker errors building Demo

### ISSUE THREAD

**Issue by valeriyvan** [hfossli/AGGeometryKit#29]
Getting a bunch of linker errors trying to run Demo on a device (iPad mini, iOS 8.2).
Can't guess how to fix this.

**Comment by hfossli** [comment]
I'll look into in a few hours. 


Håvard

**Comment by hfossli** [comment]
I wasn't able to reproduce this. Do you have some screenshots or some build log?

**Comment by valeriyvan** [comment]
Attaching screenshot.

**Comment by valeriyvan** [comment]
![xcode screenshot](https://cloud.githubusercontent.com/assets/1630974/7912147/96fb5b9c-086d-11e5-947d-31d132192ed8.jpg)

**Comment by hfossli** [comment]
Awesome! Can you expand and copy one of the errors?

man. 1. jun. 2015 kl. 13.51 skrev Valeriy Van <notifications@github.com>:

**Comment by valeriyvan** [comment]
![xcode screenshot 1](https://cloud.githubusercontent.com/assets/1630974/7916814/e434b19e-088e-11e5-872b-fe5e4173124e.jpg)

**Comment by hfossli** [comment]
I am not able to reproduce this. Please reopen if you experience this again!
